apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.project.path }}/gateway-api-crd
  destination:
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
