apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    path: .
    repoURL: oci://codeberg.org/k8s-gateway/charts/k8s-gateway
    targetRevision: 4.0.0
    helm:
      # https://github.com/k8s-gateway/k8s_gateway/blob/master/chart/values.yaml
      valuesObject:
        servers:
          - zones:
              - zone: {{ .Values.domain.intranet }}
            port: 53
            plugins:
              - name: errors
              - name: health
                configBlock: |-
                  lameduck 5s
              - name: ready
              - name: k8s_gateway
                parameters: {{ .Values.domain.intranet }}
                configBlock: |-
                  resources Service HTTPRoute GRPCRoute
                  ttl 300
              - name: log
              - name: forward
                parameters: . /etc/resolv.conf
              - name: cache
                parameters: 300
              - name: loop
              - name: reload
              - name: loadbalance

        readinessProbe:
          # 4.0.0 increased to 30, was default before
          initialDelaySeconds: 10

        securityContext:
          # 4.0.0 removed this, was default before
          runAsUser: 1000

        service:
          loadBalancerIP: {{ .Values.ipAddress.k8sGateway }}
  destination:
    namespace: k8s-gateway
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
