apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.project.path }}/kube-prometheus-stack
    helm:
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      valuesObject:
        kube-prometheus-stack:
          alertmanager:
            route:
              main:
                enabled: true
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    name: traefik-intranet
                    namespace: traefik
                hostnames:
                  - alertmanager.{{ .Values.domain.intranet }}
                filters:
                  - type: ExtensionRef
                    extensionRef:
                      group: traefik.io
                      kind: Middleware
                      name: authelia
          grafana:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: intranet-dns01-prod
              hosts:
                - grafana.{{ .Values.domain.intranet }}
              tls:
                - hosts:
                    - grafana.{{ .Values.domain.intranet }}
                  secretName: grafana-tls
          prometheus:
            route:
              main:
                enabled: true
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    name: traefik-intranet
                    namespace: traefik
                hostnames:
                  - prometheus.{{ .Values.domain.intranet }}
                filters:
                  - type: ExtensionRef
                    extensionRef:
                      group: traefik.io
                      kind: Middleware
                      name: authelia
  destination:
    namespace: kube-prometheus-stack
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: kube-prometheus-stack-admission
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: kube-prometheus-stack-admission
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
        - /webhooks/1/failurePolicy
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      name: kube-prometheus-stack-kube-state-metrics
      jsonPointers:
        - /metadata/annotations
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      name: kube-prometheus-stack-kubelet
      jsonPointers:
        - /metadata/annotations
    - group: apps
      kind: DaemonSet
      name: kube-prometheus-stack-prometheus-node-exporter
      jsonPointers:
        # empty object {} in live manifest but missing from desired
        - /spec/template/spec/containers/0/resources
    # HTTPRoute values appear in the live manifest but are not specified in the desired manifest
    # group: ''
    # kind: Service
    # weight: 1
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
