apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Network Infrastructure
  sourceRepos:
  - {{ .Values.source.repoURL }}
  - https://bitnami.github.io/sealed-secrets
  - https://cloudnative-pg.github.io/charts
  - https://coredns.github.io/helm
  - https://github.com/longhorn/longhorn
  - https://kubernetes-sigs.github.io/headlamp
  - https://kube-vip.github.io/helm-charts
  - https://kubereboot.github.io/charts
  - https://kubernetes-csi.github.io/csi-driver-nfs
  - https://kubernetes-sigs.github.io/*
  - https://kubernetes.github.io/*
  - https://mojo2600.github.io/pihole-kubernetes/
  - https://open-telemetry.github.io/opentelemetry-helm-charts
  - https://prometheus-community.github.io/helm-charts
  - https://stakater.github.io/stakater-charts
  - https://topolvm.github.io/topolvm
  - oci://codeberg.org/k8s-gateway/charts/k8s-gateway
  destinations:
  - namespace: '*'
    server: {{ .Values.destination.server }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: ops
    description: Read-only access plus sync
    policies:
    - p, proj:{{ .Values.project.name }}:ops, applications, get, {{ .Values.project.name }}/*, allow
    - p, proj:{{ .Values.project.name }}:ops, applications, sync, {{ .Values.project.name }}/*, allow
    - p, proj:{{ .Values.project.name }}:ops, applicationsets, get, {{ .Values.project.name }}/*, allow
    - p, proj:{{ .Values.project.name }}:ops, logs, get, {{ .Values.project.name }}/*, allow
