apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: "{{ .Values.project.path }}/tempo"
    helm:
      valueFiles:
        - values.yaml
      valuesObject: {}
  destination:
    namespace: tempo
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
