apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: "{{ .Values.project.path }}/traefik"
    helm:
      valueFiles:
        - values.yaml
      # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
      valuesObject:
        dashboard:
          intranet:
            hostname: "traefik-intranet.{{ .Values.domain.intranet }}"
        intranet:
          service:
            spec:
              loadBalancerIP: {{ .Values.ipAddress.traefikIntranet }}
          gateway:
            listeners:
              traefik-dashboard:
                hostname: "traefik-intranet.{{ .Values.domain.intranet }}"
  destination:
    namespace: traefik
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
