apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/httproute.yaml
  - ./resources/deployment.yaml
  - ./resources/pvc-data.yaml
  - ./resources/service.yaml
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/name: foundry-vtt
images:
  - name: foundryvtt
    newName: felddy/foundryvtt
    newTag: 14.368.0
buildMetadata: [managedByLabel]
