apiVersion: v2
name: authelia
description: authelia
version: 1.0.0
dependencies:
- name: authelia
  repository: https://charts.authelia.com
  version: 0.10.58
- name: valkey
  repository: https://valkey.io/valkey-helm
  version: 0.9.4
