# https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml
headlamp:
  env:
    # Disable tracing to avoid log spam
    # https://github.com/kubernetes-sigs/headlamp/issues/3439#issuecomment-2954604955
    - name: HEADLAMP_CONFIG_TRACING_ENABLED
      value: "false"
  config:
    oidc:
      issuerURL: https://auth.int.fivebytestudios.com
      scopes: "openid,profile,email,groups,offline_access"
      secret:
        create: false
      externalSecret:
        enabled: true
        name: authelia-oidc-headlamp
        # Work around for https://github.com/kubernetes-sigs/headlamp/pull/5573
        # Set -oidc-scopes argument from outside the secret
        hasScopes: true
