---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foundry-vtt-admin-fred
  namespace: foundry-vtt
spec:
  encryptedData:
    key: AgApS04TsVL1dXLZ7nsKrOsme2aryC37TZrJrVbyJks0jCcpJpihGwTLw8hBaF7anHsoI6a6clb6DFx2WwDIYdl3tqzNI9BGJs6dU5busxx/K9Gcwf56p6i1rhYpz93mNTyQnZHm5XL8FBdE5msesIEPTiITV4VyRVVab+eQzQt9doyps0YOVTShLVbnX/jkf8HY8TZhdnKgFiveXqo1f3ZSJKrRs+rpCO17O9C3vgE1UbO2gfSuKmOvCpNZaYKKUQHBOb0+8eUQyA9r+pGduLpW5d15/+KKt14iiMbc0RTtosjXspIDAzSswf+wDX5/4mpqqk527jfFPm5VSDgzO3JvSSwGVVzb5f+3TgL6282dtvUCV4oWEDsyl3CNlAOd4LKsF/dS3h8rezCiN2UiZ0kPjCloqMHk/Dq7UD25cU54Cog2/ESlPbW3AKqN7yAOlxz7O2J0Bfss8D3gIIm+SfHb6Rk5o7NnFBYP44k2KSOON4YnHVOLwdJ3CzkuNb74LYXsSz/yq2wzg/AkMjQHbZjmoi2OvhD6sE9Hst3jvvnYQ7H03kdr/ssS1pZO2voaH6x61f3j38g4ZVIPH6iqTM2h1NdshIdwkO60zU0zJZKvVJfTYaY96AXmxG8tGJNHmAr7KpvClbccst6mGEeI21MJdIafEvuz7NZhgagHKjZytQHw7r3ULyP1RuGSng3mPc3oRXCMCp8wFDgxCP7kqf/Err177CUokVb3W6M5EEHAaQ==
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-admin-fred
      namespace: foundry-vtt
