---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foundry-vtt-admin-fred
  namespace: foundry-vtt
spec:
  encryptedData:
    key: AgBr4Q7vr0ORXlFCo0qNFEt9RPCpxU4Sl2CvEiaUfBXwLLNHekJ/ZqEUj46tDC0oTOLPK4c2gFvGlb/H6KJ6YLGx/843+t6kAOmfH69n8dnlx+L6SJUMmlzEGx5wbfZDuTGQ9Upc/zWOwV/2h5Y/ufzTNIa4nh0PhFkAWEa8WX3H1wkU+KC0mPiE99rr9xs6hzWOC6x6yvh5u1qemzrLeaNmmoONj0Fg6xd1NeAbUfikpY7xFKVFMrPFwbqQYZmgJBEQvoqPiT+9dpHTpp7/QT7QT/1zffoI/q1t8HzhqzpY83PuW4//Un94UBxb0saPwGUQGvImUYwMiV6Kf5L8cRSLltWsdDEyYscEeZEiV3TuP7lQtHVgGctxv8Lw4G4hNGZc+kYjZBsumJYHI2LQleaVZCD3kKXNrlCqDKdaF3TiBLzYF3+f3rLsYtvnHcKu82qMGFjl4Wyg9xMLynvt1ui05H+AkC7DKEDH0hcO9oeJ8dKnEezKiJMgdVjPlqhDSjNDTgUU4I07BbsEHFi/nTp28cg1plfLv0f1Z/vYl0xw9fl6yEEgRGn9057YN6n/EmZ2V5tgYmJIdZIfBBFa/X+VmgK18WxGGsAIbCz7UOhIYz58eczcGgQk8uiNRVipf4bbr84x/pWmfRx5mN1axShuD+7x6xzNYyj4QJeTlMq0H2vb4QjoIL79AJ/Erz0QXJuOSA0pZLlEBUdWRfMK5TAQK2ev5qFDZnnYJSX1o6IU8A==
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-admin-fred
      namespace: foundry-vtt
