---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foundry-vtt-user-fred
  namespace: foundry-vtt
spec:
  encryptedData:
    password: AgCpEulUko7zRAbDlj4E8uW49uTVeHbrdG4t8w1XiSTIdLxRZkh4q/J92Zin9hSbAvAb1svpScFwWDTSGI7FLLoLQu4vrfJAVxyjqbSyw9+f3pSkQZf78OPbzuR+sCvjn6Su0p8rXtoYApuY+vZVLj79D6YXBgOO6q+XedAmFabgL2t+cQ9ScPS2LvcWasJ38i/wVRBBiBD/BNxFTPj3WwfvSsliS3P1hBCF6UEsikm1HJmG93mDtcXY3HBSlkx6KHvYcxQPxbpHyMBP9k/8wVj+nvSU5Q090iRhChBus6+TXVsypEXGhQ9guR4tjCFmyBUH0a6z9ZcSlz4z+VGBvbwI8donCQdWWS33bzF9O0jdZs7XhCRuHFQiSMY8SGXpLR1IVWSQ9sqhPemQNlbKpONU6ifdWlFY7eZgfkZitE8xuzJEQxtM/sO7mPgPwjAjPNEmqcABS2X78iMRAKKjPkepUEN3WoVtpdJEd3uk/z+s3ECj0N68ExusMoa8dxxfeys1ZlN8AMWUg0wGOX915J0XAe98lS5n0OX67hzAdGY8/HBpqMik0o6DCijMhYQYIkn2EfKeZg/Ry1aeIcWBXbJkBIAfDATAt1aL9ETLCWiZHCWtNgAKsrpAIQdbRM1fXkwbAAKCFK5Jy7jDi2ge/+QiA7R4280pdbiJ4zzGyWyn7WxdwGh45B7Fehu7GqTF3hoRukv5al0gtOpfJG9Ev7cV3mEpO/RWYsPk0S+siR4SJg==
    username: AgBFwzKFcnYIifUBRWoKKfpc247LjcVpsI9OApkCN7NuD73y0wTSueSpnr6ddxtHB6nw37x6UQe69HwtFY9kPJd5bn6zVZRiZQklBJ8+BYozqkOAtIfc4QJBQKfs79em3WUEsxI4mpEmtuuLGSseLWJam6pytr7V4Hj2/8a+dlvYrSsHSte90oPY1md1QK1dCXz/1sPfl2Ey3ow+0/BONshwk6eMJnWkTCvSSH8qx6AeNEZrd3GZqgf1m5OPpdvfnA/VEkQvx29ypNjJsZEL/PROUYnR8nLyzoyISa5QPj2j7UVQX7d9hBOKZNTqK8Xp2D24BNa+GHom/lJaSgo8S33cvxmC/SeTnN9NrUEos7HQn/5YlOrFET0BDQq0f+sQrp2S65lc+Hj5YyMGFtn8gsONYGpqU7HI+GIp2acdDxvvDuCnkjXkqGOB74/DO5vB6tpc9d0Yc0eLKH0qQ7va07u7lZPWy6RD8G26cqZETaAqIqSpK9GslIiGyeiGG+LRpiCMmz2eDy0ki+VEa7Qfzt9THHJMaJ3RZqBuL+8qrHylArfc+vavIIMGwlMxzjLpJ4vi6Ti9amaXJfOMqGiv1j+dT1nfg70XwQvj1/dxHkt9ZxMKLFYebGeMmW3a5/6K4lc+6DZng4P+VrhiKGX4aGgV9nTKLcqNJFJAQNth869UhFVZ6QcDs64DUs3qQ0G0NJbBPg7ZzR2qCnbs
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-user-fred
      namespace: foundry-vtt
