---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-oidc-grafana
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgDKA7FJb45ZcYw8GoWuUNNJuAb28FexjyBe/Kpgil52+ej2Jj7DvG7k52ldt7DrYN2wCb7flmLQY8PDDzM8LHR08+Fqw6FdNVUSClRIWe2wMtgBl9rnugl3c+PVysSa3b2vTdKRCz53tUYmLHkCPkhNJdENNrCw6owLweTSdv8Iy70LMcPKEvvP4FcPxlo1Tmoxwm4OjOsJuRKpykx6J5YEwwTTYoV5pdfH9EZ+vRoUHH1ffT32VllBgOX7tpkMagrqUoy04qNKPda67Z5vjotkTtjHseQQOmIf9OucQul95y0Ytng27gew8V5rzU68a/LYFVGEc2k1X2FPX6RSWBQ9ATXGLfgti07Dvz9Zr5gMtmBTSxdNb/VlB3GHIlzKePlXwN3DShyvFbome6OP9zqSayu2s2ZIig8A6+jP265Komlz4mWARsS7f1Pc+Vr1KRpg/8ads++h8Ak/M4exf0/wGl6qC/bnDjBbQfO+g+lAcSMEW7ZmUQuEZ70BtMU2bExmSWsSLCL2/odH7KIGNAok13OmTqnBeOlUz9HlYNhFUk3hkVwTOTM3mKv9BlJY+YIHH4Wi6IfZi9l4xs7IRtewBY4Rs6Ki0YcqTg7IX4635cah8lUalKK5msZ/nSgdQa+LmcV4ky7kFZitXZwJKLFK5R9rSfSzyUeDQbc3TVrRtF64iwzw386vSQYNFdseU754HyQp+Cpm
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBEwEsTMXUKwXLRhSg4EHNGzED+IKzWRSuOLH7PC6CB4sEfKuM/LVdAHTsC6yuwfjcpiiStQu6VzJCQGy1Txww25957psBFbeiUPQVtRnL+fYYO0nNzIEVL+6j5EZpQ55SJXIxGU5uWir7wwglFNOcZF+169zAaH9h1IQ7qgHo6AiEsuEYvc1RBi6NTQX9KfF2pXJQ4X8M2ShpJfY40IJMu0CsNNxv+vvdWOKq2KF9qAg42YMcZvZxF5YACz+TNtk3kLdxYjY2u8EWGyEXlaTgboq8b1Z9O8+oJ1u8nV5W+5LufzDwy65VyTftcxEA1Ltkjl7S6BqJBxJWZdxFJlBOfer793duGLuGcQO5BQ5VVCvlBEWnmkahGhhUDOSTGzEISnTvoQqsNwM6mjhnrl/O8TldmMNFIdhkT6qrg+nBtlvDydbUmnNxtdRKKObY7T61UW4XCxBa1HXIfNamu442VI/xmBopJwnIFn+Jc8APRZh3vEm4ThqVntSfPWYYIsQ5cnlkHXqCib63I1LXtd6Z1AD2WM5+4WuH23u136/cBF77wG+S17zpS4RcomLYWgbjs2daYghTlGMxPg5Bt7nurCAZ0nOSNw1Ll5+3PsIRUi5MBS52bbxrZkSQX2t41nO5jiZquAUVIfAHsRTMsw23ULFPYhgl5Vm654JPkxH7ICzmaKqyzD46Ci2BoF0vg1VXCbJk9/Hiu3um5B/GQmrE2saAMRihsWdo1I/WtrdU1O6wN55jLlsjKh+nHcA1MHH0ozZkkyPJmRk2BXoErrCXUBeYfakUjYC4=
  template:
    metadata:
      creationTimestamp: null
      name: authelia-oidc-grafana
      namespace: kube-prometheus-stack
