apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iperf3
  namespace: argocd
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.project.path }}/iperf3
    kustomize:
      patches:
        - target:
            kind: Service
            name: iperf3
          patch: |-
            - op: replace
              path: /metadata/annotations/metallb.io~1loadBalancerIPs
              value: {{ .Values.ipAddress.iperf3 }}
  destination:
    namespace: iperf
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
