namespace: metallb-system

resources:
  - github.com/metallb/metallb//config/native?ref=v0.15.3
  - resources/default-address-pool.yaml
  - resources/default-l2advertisement.yaml
  - resources/reserved-address-pool.yaml
  - resources/reserved-l2advertisement.yaml
patches:
  - path: patches/speaker-daemonset-tolerations.yaml
    target:
      kind: DaemonSet
      name: speaker
