apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/deployment.yaml
  - ./resources/httproute.yaml
  - ./resources/network-policy.yaml
  - ./resources/pvc-config.yaml
  - ./resources/pvc-torrents.yaml
  - ./resources/pv-torrents.yaml
  - ./resources/service.yaml
  - ./resources/service-vpn-http-proxy.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
images:
  - name: qbittorrent
    newName: linuxserver/qbittorrent
    newTag: 5.1.4-r2-ls444
  - name: gluetun
    newName: qmcgaw/gluetun
    newTag: v3.41.1
  - name: busybox
    newTag: 1.37.0-glibc
configMapGenerator:
  - name: qbittorrent-gluetun-config
    files:
      - configmap/gluetun/auth.toml
      - configmap/gluetun/update-qbittorrent-ports.sh
    options:
      disableNameSuffixHash: true
buildMetadata: [managedByLabel]
