apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    # The default project is built-in, so its ops role is defined here rather
    # than in an AppProject. It holds the app of apps for each project.
    p, role:default-ops, applications, get, default/*, allow
    p, role:default-ops, applications, sync, default/*, allow

    # Authelia (LLDAP) groups
    g, argocd-default-ops, role:default-ops

    g, argocd-infrastructure-ops, proj:infrastructure:ops

    g, argocd-media-ops, proj:media:ops

    g, argocd-play-when-ops, proj:play-when:ops
    g, argocd-play-when-ops, proj:play-when-dev:ops
    g, argocd-play-when-ops, proj:play-when-stage:ops
    g, argocd-play-when-ops, proj:play-when-prod:ops

    g, argocd-services-ops, proj:services:ops

    # Local users
    g, fettinge, role:default-ops
    g, fettinge, proj:infrastructure:ops
    g, fettinge, proj:media:ops
    g, fettinge, proj:play-when:ops
    g, fettinge, proj:play-when-dev:ops
    g, fettinge, proj:play-when-stage:ops
    g, fettinge, proj:play-when-prod:ops
    g, fettinge, proj:services:ops

    g, gabe, proj:play-when:ops
    g, gabe, proj:play-when-dev:ops
    g, gabe, proj:play-when-stage:ops
    g, gabe, proj:play-when-prod:ops
