apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, gabe, proj:play-when:ops
    g, gabe, proj:play-when-dev:ops
    g, gabe, proj:play-when-stage:ops
    g, gabe, proj:play-when-prod:ops
    g, fettinge, proj:infrastructure:ops
    g, fettinge, proj:media:ops
    g, fettinge, proj:play-when:ops
    g, fettinge, proj:play-when-dev:ops
    g, fettinge, proj:play-when-stage:ops
    g, fettinge, proj:play-when-prod:ops
    g, fettinge, proj:services:ops
