apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
stringData:
  # Fetch github webhook secret from another resource
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#alternative
  webhook.github.secret: $github-webhook:secret
  # Fetch gitlab webhook secret from another resource
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#alternative
  webhook.gitlab.secret: $gitlab-webhook:secret
