---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-webhook
  namespace: argocd
spec:
  encryptedData:
    secret: AgBZpkvWO4zm4sI6WWFvG/+brzQ3C2tqCS6SZ9Em5vOWpNkWxWz1Kn0FnPJASBbDM/IMUBo0e5noayBw2UGMbktbNYS5QjANdkSO7pXuqkb6BRItNBxXkffePN6MDL9mcyUFT1T93Y3EAsvG52XIuI0EdHTS2P7kpTZGsDj2Yn/sNg3WPOLh/BdFNRlYFs8s3SSTGxr9oB5fjaccvsDCml0JVkhcTCRLMhGfAmjLcu5BSqZRWtot/2Zpp13DYSLe7JCsSLQ7HU7FA78khNqyDOtc4zPH8HFFY5uCbc8n4dnFVw5ZdUWJmWvyVWS8Pu4T5zl4FTnFHyGJEBxgLIHEDflrr97hxLrU5h5RKIDWXM9ERNqnUaJt03G9AmxFpPI73M3jtV3XVxA2N6Gb3xHwR5r1NzMVBqeGtUn/HmI2kEe2exer5UQlJB7ufZ5Bon4JjryDy5U32Uu0jLwqs+eB3wemeIOElMxynCdD3XMb5WuufnUbaiEJscN5JChllU+RhGI1GRFO1EVHe6E1ke51aNQMnYitaniFxUj+CT1GFk1urakZ8XCRw9NrKT3TnkUZrSADVdUs5smqRajgwHN+yfYtSXSsn4xFb1qa8LsEMmAschmcWuJUHDs7IVXeBZZ3qm9AfZMtPJAJxlUvaaNZ9d91hf+2YXNTc55zeB6hnkZQfexb1h9xUdo68d5LCBvqliB30pq1M/zeXRWfqPubyolTt1wdrM0o2ryCk+mgngup+1GKV9smllHiJhLPUkFaKeij23JkmDbRXQPtxgoTZ8u4
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-webhook
      namespace: argocd
