---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-webhook
  namespace: argocd
spec:
  encryptedData:
    secret: AgAaP9ywQxo8GgQWXAiWXKN2LuBmh8T5yR/gYLSlvwzCCnHzMkVcOHiTrydoMOGOdEkvvNCAkKS8Pd7TG1cQzBIJXu/jvlXCkQGok/7Lk1vT5bQcJdpqiBLFxzOi1aLK8ti1QOS9WqdQajJJQiJMhCTSZ5JSuCrojF+gTElXDZTxq9b+8LiQJFSRU6VowoFOK0vamF4xaQyoyxfQB3dSnPU6da5W+YKEKmuP23jzM5MIEIK4E0MnoGVw03UznCR59NHjenPGAVv8Ic6dogC/keV4nduO/J75GJv9fAH8Beaj+VsLEq9N9nRydYN7OrYMkR5rsq/7IcITxykvp795Icj9nQ/CNJRldyDA1Vo8r6nDTvIlb004t9td3jMFLB4yXVofSl0oC5cT8BTPpx9vpUYwH9eEm6LVtPlCkmc1LHvXz/t4+rdc14MIxuMY5KXoXt1MmZOTqGa1XTm2NasJLZLUsRhSXQe5pMMxuSZhc5RJ9o3P4w3vbo95un3EwjsmQh8Xaw1WZYP4g5SJeEsWu+MFDm6S4XTaGvdt1G94A54MLrcuoQVqsKX77MZOGatE34o2xPq8EareJOBfmQE23K/AnaarVyZKEJs/foOfLXVYDWJo+mphi8EL4M3+/klqywAZRX2z/IYszqxKcWplbp/msBFGMgFT0mvJQnUCv/NOgw61INNKBWw7I40DjDeUS426c+bT+NqAikCGEsa54Y0/24BZHnsAuth8S3BhUnfzMK5d3xtb1mRD5vP81Q/LUWwwpuBZR6IBrYw4WfJ1h8Zp
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: gitlab-webhook
      namespace: argocd
