---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-oidc-argocd
  namespace: argocd
spec:
  encryptedData:
    client-id: AgAp9ovD08eIlwVwBcWEkJ+PvnjHQFVYXGtyJmQpHaYkTfwz98ycYAjtJQUqZmGGZHhBZ5dvhCHyvRyPaUhiyvQFuvpZgt4Am/VSeHJa7Oo3O9qSSYwowFILrYAHzdYLzsgc/0HWibuTMlKqPkHqMLvqKqFVuVIxUKj4dQuZKtsZHUQ8rKkZxK6pdfup9bUrDw8wubXEaUxrYbdcJ2Gj3sVZO0mkniQc1TnBcPG597ec05MpiQZS0hVsqYPxjKKXvNPy3L4ylLxMhzNgOoAuLJHDWDLWJOrnkeXD/4VhcEVFwLWL/3QW0x/YI6vB0zl1ug7dLPWT4WGfS5vPTxCSrdff8iw7PuvfD2l4F/Par6TZ3i/jhY/SToGqn73W5avb7CBQbaZbaT8fMGt3PM/Eibk15qnqECQdwWQRX2gYLs3JTmcjq0d0FFAkNu1mzvvLvXBwwxpfMuWljZ0uv8DsLtanxJ/I0Z+qKDchZSvAwIu/ERuAx3dKBKK0655ey47ynq4ntjLHAYf21qXQ7p3rCH3kX1Xs0uc00oELBj6tfLHdfNsOxn9OA7flUQ+/vlTEzdZdtqQFB+Um5d1gdm4Myd63dk8yIu2x9HHhug5LTZc9car6x30oyythnsv9E9ED3GJbb+NWzkJVcVhZptXOIVC2tynfPC3fhlrsHNB7riFzqlaOsTBHTsL8QCCSbVWpR4wC8xoVibw=
    client-secret: AgDuXiL/u8wFgdt6bCCRk8A9VQGBvVVc3WXzs4jr3FYYNb8rf9hAROcRrPvsZKe2gNTyCWYdgxh+S7t00lTPvkFM3K0bYZpOc9HMZwt85GsZ0cuzV6Zi19YNs+54x0HQa5zlncv4SReN/NFTitWVTwSAkiZdf7rO5SoZUtgmoHPHS3UeveN5EINjBzqTJPOI4MZ5hbon1goo68avx2+W/bhqZE1lrNF7bsC6Lk/FbVXB1ZRYaqABek9bvOTZBuTVwtiElGB5JT2LFd7GL5yFWoTQ567YGU/CmE3BBV8WWLcXT29MikOlPNRp8M0VQ82B5gkmycC+JvlpjdobBC3IcoeBIkH4/L1/zXCyxF/nP9Fls4TaYQ09sWdSgnJAisGnBL6tBOOJbPRBj8kNMgUS9DqAo1//61Ap6CpNhEm92FDze4U30yFMz6KtAm6IRz3eRbGEozQOwvtujOBKqEaRG3/48oBuQccBSwfqdujAZP0bOwESLdBn1aOHg5U3cDYovQxH9FkNfw39qy668u8gHrK595/K5qfSxGbhDjeVp9p1qXL4xjoMeITO4zjQH+b81JeiH1BlIjWkwvYXrHDwb/UFEUovB8ED/AgTE7F9S644xyGQG+JmfTthb84fU+vZ/uHFHEPh7rbGqYTFW3f2DM9GHAqZwX5ResYMu+NhD5xFRv0IVFaN143KuSG1Ujq1sz2jOJQdqokFMeYNTfbjwppaAK4yttb4HT9n5Kxoy+jhjJ5C0/1fA/93fLXkhJyQ4IJq+A1i9FLbT0BSkv7kzjibesRMmKQzCFo=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: authelia-oidc-argocd
      namespace: argocd
