---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-gitlab
  namespace: argocd
spec:
  encryptedData:
    secret: AgAbn+CB2/o22JB29s0K1ayIMJBeWvD087+NpuQL6QWvlp4KgNWOa6Wc1aRpbaIaIYszcJvpl8xuBbcJUpwCwZCz5Gha+daeBRb0YDk1mm9dLO2qMkUdWZMhl+TLquc/HxoR4YQvF7tOseyLeS8HH5j2E60M5jBjXFIzqdVM4TMbP0GoJtDbXCfBHwe407qoVgsBZsByF1gIyu8EoDIK5Af2sAtibH2YDP+o5nwmcKSM+CBpY6QiVsC1rN/0bWroF2Ti7TLnds0tCSv4ij/JSrhIFHQ3JGtfOWqhHw5xteEcD/IqwkVPWgg7coeeJp08uBxZ5rC1qOydnGbfNieZ+mWOvKYgCxx5wl6LstIz6tDkd1y3lGOc9gp5JSxT+aB39MIIvA3ILOIElcnqpBXlvWGBDgodrdCf3HfrnWjqDMbUnG93NIC9d1LnUU2sYOt9vNtvnW4HyvsM/ZVCzRGQexSmrxbj2JR/CvY+ZWP76WotJmJKVU4ig5voJaYFRKNlo6/13TwFbjkF3R/u+wFmFBbQXi6sbNgAT6lrday/iSOz6cye5kTMF25uxF+tC9kmhItMVnIb2jlXLgiIEwJusACFILHJWRQvVSc2jlE0OGg5rp+2KMSybJdBy55DhU00Oyn/YfHsfsmu7a2BvZ7EP7JS3s3Db4ixLxWPcQZ9z1BmxJC+REzrmij+aUs62oO4kGhfa5PmQMO6dVC4dxB42IeZKuDBM+RppoGbDMDvg6TerqaNQMCN6HeRgsExg9foxVK4Ny7hH+uACD1W/88TBBp0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: webhook-gitlab
      namespace: argocd
