apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: play-when-stage
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Play When Staging
  sourceRepos:
  - https://gitlab.com/play-when/play-when-argocd.git
  - https://gitlab.com/api/v4/projects/46393971/packages/helm/stable
  sourceNamespaces:
  - play-when-stage
  destinations:
  - namespace: play-when-stage
    server: {{ .Values.destination.server }}
  roles:
  - name: ops
    description: Read-only access plus sync
    policies:
    - p, proj:play-when-stage:ops, applications, get, play-when-stage/*, allow
    - p, proj:play-when-stage:ops, applications, sync, play-when-stage/*, allow
    - p, proj:play-when-stage:ops, applicationsets, get, play-when-stage/*, allow
    - p, proj:play-when-stage:ops, logs, get, play-when-stage/*, allow
