apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: play-when
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Play When Project
  sourceRepos:
  - {{ .Values.source.repoGroup }}/*
  destinations:
  - namespace: play-when-gitlab
    server: {{ .Values.destination.server }}
  roles:
  - name: ops
    description: Read-only access plus sync
    policies:
    - p, proj:play-when:ops, applications, get, play-when/*, allow
    - p, proj:play-when:ops, applications, sync, play-when/*, allow
    - p, proj:play-when:ops, applicationsets, get, play-when/*, allow
    - p, proj:play-when:ops, logs, get, play-when/*, allow
