---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foundry-vtt-user
  namespace: foundry-vtt
spec:
  encryptedData:
    password: AgAoR92gY10HDuFJV/ASM/YFiC1N8xmrzo/GgrNkUxbqFukmHInHbvJfqgKk2VqzoGClEyyEWQdi2IXerm2iNZtHYZG1u0Es9KCpLMENH15vBjO79ZxfE6cdtUu4WrQ7tj4pUBepxdeQLjhy+8fi/P/89O+rJJ31xMDvyG/WidbM3NdxuOUVewnnxEGHaQrEgEPF5r+o3PBK4YCwue/6wR2bB9datsVwUz+bOpFfztxxJKWb7IlNh/MG3KodnRuPP/5BOWYztDWHZvi7Sg/SbxnSSDkOhWTiAoGYMKWCQQMGT8HU/l/30PhdmWO8HeF1c0Mm6T2yTNwxuD1xzzA+zji8Ze8ilit4ZrFfuqDqR4oJ24T/Ecxww/NbeXJLwn0mBWIWXwd1S+4dupJJOXXGVPWlZioGD/d34LLAVt+BtGQQ2geq6pT2Wn1riJHvtDhMnwJKWhBeXmC+PyoIPLGaBYm6N3XgXFdKyytON+z9p7BmGzQNY6v8tRNOvj/ifUTS4HWz2+Ny9Lx38IGeduQXUJtlMKj8mw+HNAJXpCXD6hob7R8sf7pEydqoS3KuJxnWjZUDUIsvrMN/8FXv+UafjkSs1spiS1mGhT+Na1K9q6bDwSTPItrUrva6sDZt5eJRNqfH5w5hZezifD6Mjy9f+dxLziiWBZFAduxfwpwkHUJ4N9L/hYt0sn0xYTD6KRkoFoVQDMISmP5sbHpihJCsHvYjCxAUW4scayVzSu9LHgg/JQ==
    username: AgAiiZYjkQ4RxfBjRnWp91AOvcG5Rjy+ArkVqaZL0y3D2x2sziPnWL4noE2257a7GGGr+dGCf3aQGk0lYX5pKwPdpUBY/uEPz99vHt6K8JwH/LOlm1kFuEoJdjQ10a3BB7jgm+FKLJg3bqt4B+VRQLB/cofINoXLLjdF56bBaIUuDjXoxZlaCem+GISq1e7rsjkQTfV6jL0FBHUd0bbpHGorvb9/C03iz68p+vzwXLKL4vwoVkJ0Qidv5e/aFJKqQ8dXGJDjYGYt96cKf9c96Iua8emK7cDi8PEKtL+kWp/3ndnMrdCBSEBZ942hYkoUVn3mL7ToqVhJaDOy6XmlioSiZAU3puB1Qm1JMPFRcip9W6tFf70MYzoI0IWbFGdhnH4r55gW2HRiQE8zY902RkMVQNliKtMqgXc9Ke5RdVPxnUFNn+7vFdtn87g4OxGb10WCC48oBOp+YTJkiHaF7TDpTtE6jWx6Qa+bvjoqP1GWmuISyO+9kt7L8HH/JPkguGynVEuRJee+xiLwfs/B7q16FOJ943uwZTCTe9zYWRftEThphZ5L67GFr4Mo5yDBmRhxpSvLaS+gvhpKV8KVvAWTiWrBGCl0JSKRRCc/oxbg/mNxDciV5ZEU88K2wEg3wf2UBYwHBTxzXgQ1iXQuhD/qW+QL61M+bx0GG+FlGQgz8HS+6Xb/nNZmOdwgXEx8GnjcdtauqYtOl58m
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-user
      namespace: foundry-vtt
