---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foundry-vtt-admin
  namespace: foundry-vtt
spec:
  encryptedData:
    key: AgAtqxOzmJtCxBae3sD/0yv3FVruPYZ2JLTExCMGfXswRAxOHv8pCiQKB5M+BuwVYrw56d/yiU38EzcAOQNId+l6jHrJ+83s73WKdWzVkPMmle+T+31cgszNCQb1ZZNiJGrghN8wwZXxH8o1smOQY2J7/dzAQ+qC7rLGqt1Yg5u8DXSWQI4zBq4yQnF2kYpgOhVoYhED/uspaUZkxM6mDbU6JMUUiOyhWr/wreQ45Y6Q2bCnpefBWePRwt7gJUmi/uB22xLqFTkrcwRP1dhZvPbahnV3FC3mzmGfJjrZe/RsETX4riaXkRl941x6F/xVS1H8O++TIrW+64pEvhuOKLVSN2VgiRqdPlWOCQjklxW9jFSGREReoeXM8uuLDQlICVWbSEow9xrEMCDvyHUe/5oIjpApSnAYxGqF/ltBwoyUj9mmldWi8LgJltbVM6pfAIJ5H8o0dpoQhSHnByLZSVH2xL+oahPolldgbj2GarnEhv8NrRVJEZOcTpDmpMkMS2dK+K1OoxpZ6ka3AhoM9bqxYJIrNL1qCC0BwGazGPN6XBUbbOTvTCBUYfBlbc48lsvjHZFhGCYBFvwl2FK+Nz/9Jc763KTLyZKbcYcDVo/M3BQIfU8AojFv/y0p9nDMa5cX1Hvw6Su5fXkNr1Bzpx2+aeRP2nL2h98TALVWuLwqfTsD8CJViS0bgSe0Oi86PgpUs6WdnMZSYoW4vwfsqME9CS+MoyfunI5PnL9hV0mCHQ==
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-admin
      namespace: foundry-vtt
