---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-oidc-grafana
  namespace: auth
spec:
  encryptedData:
    client-id: AgCiDBs/8C5W2tk0dYS6pr9aftdJuRljnvEbt6QuBaXObvezhOOzckhHSE5qxRDLCaY0zr6ExKXKR9L0sWAfUpst+j2sS6R2sXrbdj6zky1CN2psVvNkycH5ikJ0w449NNWCOKijo8c3OF9f3fxi0rdxTMAl7d8WDy1K4RSfa0OEOVHTpTzgq0J1+eAYrminpg/VwHbMgPt1Z49mrPox/msbSQJA/VYFSek1Yu/sUa+2Jac9iTBeCUUPVS+QE2RumtcbwXvE185nOdW/1S+xDh8oFHQg7EE1G323exm2cmfwp5c4Fa+rOB9oVrVCQwyuOi+1rcHc5LPVWO8eLUtwx4sdA95/morYXuqKz5eBpZF/crXfotkwKXzjBUZw2wezX/1nwH9AGyVvsiOaJfk+PXEmhCI/RHV465I2WzRKS7yYly8I9+hSDzaCI+QISuBjoDK8Gp1Nj0h9KRgy4ggJ38PRduhE82eqEuChlLm1aux6UkBln8To9/FGT3eOc2K2QR7tfa7yHAJaMpnn09h89AFPq3bjrl5gqpHUxvFrqvy4KFkrFHqUOFUqVlMvz1L3/h1F96LPKVE6WKz7S+8mMl+NDmP76oXLcRmvWSVYXu3+kmH81ooWn19RTQxDH68hOV/Hs/dcsaODU5h7hvRJxVOJgEGCOxnLA/kiZxb8qszY5YJh1iagJQMYJAFzamiF/0AOXQEF9xYi
    client-secret-digest: AgC0ZCKpBVewbcT+Vadvue/ZftA1De0uC3KzEI3RiiCHsLKwheCFI+cNmqQRFNrn6q0p5Lysc4FWZfUmr158frrdOqRE9cmtGTvH4AgbYjKc80wmxduTaNmafzArR5mkPUJZ4qL+CYuVzt9/fbbYCK8Hr9zc98h+DLYk7kk8DF25FAhfH8x5xdmrWyoIeW3qN383LKy1UHr6ni+Y0TkASggzbzb2i3Hvw1EVqo+075wGJ5beyAa1TxFhYA4ishEOZwsS5JU8+lF5G/9ZN+f5+CWgvXQbzjA+DMlEen7FsPGAzKunVIRiGnnqm5zGooVDH0Hmi3FpyipX9w4NEuVehE1s8KTHPuJHIBAYjcX9eOix2kz9LbSn025KEIMifMWBOy0S3FAXy6cANepV3V9dLYbLJiK9R3TxSSAG0RzSuzrfBekTZr4O4oktzXP/5AOyFY4AxCgu2ntktK3fxDpDN17WFQ8BdNxIRW4waXRhqkphuIJq+nXGYGDIfejh+QuU4SCIXAzhBa3rv41I7oBFSMcpz/4tF7gAX9lOZ3nxcLE1Tl6nV0zOMAZhEhhT+Iv8TZo385WT2Qw+Pz2OULNKvcqk3RQX6258sgEs02dNJwwccvGARxyEdCsN4Y9S9in35psC71jDDCUvVPNWwzKxA+Qi0c1yJsZDl6WQlwzBt1ZdHGeV29yQ9NyhMif5TdlW8vGmyjCU/YAWR8z7owaVg6wauXeTMpQsYxgRVBt8ThNOkcqMGfo6hJyLZ3IKyt2L9TDYHeChOgl5aHev8k9swZ7Q3WC/Y5qRGW5THEO2pGjzqLeY+li/Yl+U15gbwr/UPP3Di9oG0tDB3R7WfWAYpHaMK/jIYGQsPlLV6tGp7ruX+C8ApQ==
  template:
    metadata:
      creationTimestamp: null
      name: authelia-oidc-grafana
      namespace: auth
