---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-oidc-argocd
  namespace: auth
spec:
  encryptedData:
    client-id: AgDRFFIlpFkDFiif0P9tEMeCS6dr2ulG3WLHNAgh+sw1OWs9bLCORyQoXOLusLSJotvYk+zZGqRozBnezFkBQfnBHkQm/8ShmrWGed5xsXQdJfWANoqudnKpSBYTjOrnyVr9Y3lLM6t0XZtHjqG3/JRl6najxiIGAz/09H+Ply24/zhLYYEb8S0RTTWUZjKtGQ4cCYEghqICs8Vjo5yc9pITUsujga5H9xOdQWMzpKMpYOQLrXZ3DzarLhHyhpH1LBOg5qlVjqi35gAGuO6CRUpXj73AlYQXqMamHBppANzUGMyo+sqLPCdon7sgb1aXIlOHsDygo1gDwcKvlvLYJL1tn/exIhZ54Ih4itNP21sfjggXJK6fY9xOIA8cNhebmnkY9od55sN0+taIcheK/VP8TZJKWiyMlsgHQn7rsgZwIBZ3xQ6FsLPEHW+xGRiH/D3SXPmo4uJIt0qrBK0fCkoCCnafW04lAAzxxDAYZuF/ePuaT5Pl6oye6/8FmqsIziCXMv8m1Q5ncs8j0/ENkuniW0HVbncjmbleGLJ5hsIjdCHIbfzvG0TiUvLxCQuBdZHd7s0hEVq3w2i1bn25yrCSM6rmYpDsPX61KNloRWyxdGUz2D3vd/Mzh2ACHgYttOD8NHp+fFGWYfNvqcSWkNwQMIkJ/VMR6ZBqReT+wTuJMZUg8Xjl7QDE+Qj6RcU6/Q63P7Zm15I=
    client-secret-digest: AgCO9zzMG+O+FRxgKo0BCbzC5J1rdQCDzIGOTpPaFPXJVUuEFUncBrmDR52pQt+34JYHVb8xJS5Zhz1IzrTzrLZIM3FHkFQyOOmoc/qWpnGmMCUpz/YBf03vHfzUDSiBEJMy/e1354GhokXyyjbZmu9BY/p03cAP2SKgRII4cYMmq71C3jN0ern8zIfFIQeSJTm12hrMTY2LdDzlZFsTP+PBF7vjMjbv2toNS3mJ4LObWHWcx2BCREdV6jY3i/w3L0oEBH/RasmtwEArsMLi/+EQgzk6A3hkCYzwUVmejtTLOwEJPQ/epsVpfVYk1qiSEmU0oXvOhUG3y8xb7cQfJiqlBp0wZv7roaXFF/5qo5+pS5pF0Lfd5ZyN3eN7ys81t1YXm+P2FkHgqyHpN9Q8DBkWSgi5zdnEopvWTOt8r1+Oo3KIwpkEgt+NizQsAi8HD87PsTD6+PtssfY3D0jO9NMXYE7kAd+paBixW2TNlJVGRGTFGkar7Mv3Iqd6A2YwnFZvedqLJveI2VH1B1Ftmr6S9WdBgOCC7Tbsg4GisxqubS02miMepT/ZA8WIKzNQuPMtZEtA67awGYinw89HTaLTsM8DE78xupesQTVDWDEMdvdKgjbrXQAjhfhTnuc56K2jIybQ0JY+qKBkQ9K0BW1QlotxvcZsBxbIgzjBFTSsXDWtmYmce5tTKJ58oOvnJyvpwAiMUlUVXVzl8Q1m6+w7iQcqktg58eTMkvxYBgmUnWp+85xxwaon27ZtQ7a5Sl/C2AlPTSlsYmsseuwKbn1eVRoeL8lPwYkGQhFMVR+l5W9puGdNjrIzFL22zIjKeeITQcqmYojgZbdMCMSbgnfJ+WVTj+RmH4wR9poiyzLXM2lFlA==
  template:
    metadata:
      creationTimestamp: null
      name: authelia-oidc-argocd
      namespace: auth
