apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-vtt
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      containers:
        - name: foundryvtt-web
          image: foundryvtt
          # https://hub.docker.com/r/felddy/foundryvtt#environment-variables
          env:
            - name: CONTAINER_CACHE_SIZE
              value: "3"
            - name: FOUNDRY_COMPRESS_WEBSOCKET
              value: "true"
            - name: FOUNDRY_MINIFY_STATIC_FILES
              value: "true"
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_TELEMETRY
              value: "true"
          ports:
            - name: web
              containerPort: 30000
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: foundry-vtt-data
