kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: foundry-vtt-data
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
  storageClassName: mercury-nfs
