---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-oidc-headlamp
  namespace: headlamp
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgBaU/n+P9moWjwuOxxy4YRMyYKS1hq70Erj82Bh8vb2ixkoOLgtFg5lznodBRNByJx1rOABLVgjoR1IitsFpbH8LgNXyq+UjgdwH84rp4vLjmt0ynhaauTImTL1xY9z1qEcr8dLhSyHiz4Xlz+6cMWPZx6s4gHaWLbJaodrKnS+wxJ0qvNG5iDt8+ioTs54MbdMTuTTzedSkXDf///3SP3ZCrM5W5bjfiM1wGGfNxfCw5/WnYziELHqonLXfYHJmWt5WOBoRAfirfRc2uS1hxp4IbWHzfR6BdSyx8kLF3Q1XCnuzCTMbYFZ74BztSqVaWiJmpqCjsI7RQmGqruT9Wlr5lt9gmVZ7Sxo/yL+FbzebLBMTZo6tdp+zNStokdgJoW9Q3zPWs+QXjCx22IMEaSdDal/lpVpqinee16rpx/m6BlYCAkfVx+gMBBN4F3KdBNeriK9/Uhoy84MvxhbtEXFqNu9sxDV5IvJfiOQ09ZURdBel39fhftD9xP0r8Z2KtGD4Cvkb05+5yNAg+j6WVZHB4RbgHqHLoReE6sPEsWnKwlKOm52xVxH9UyYFUwkCKy8oTzt7R07YFGOF866fvZjRnF6c9GCEQF9l1Gbt/KuUdxOFHVGHWGbH3eG+VTDmb+B/Z8CJ4Bld8M6aYS1gu6Ovv0VsteMGLZXP5yX4wgw8qMHaR20WcTawZYL3zVelYZmuFPtB3CNRA==
    OIDC_CLIENT_SECRET: AgCtGN+56+RVnJo4ZJH8GObsuPvwDGJVIhLpA4a4fI118cYBxPk/0E+1DtOO9VCsPRFZfgi1relb8KumoAb2yGAaykALqENjGSxgs0/EUxvYIgjoHqaMij2uov0AvOXMkQOanuE4Vf/JCPJGsWKHyjy5KpXF/OtY8Vdh162Farij5zvq0sdTDGKjSWgKISnCMI1P9HflBmmcuvg3WWqz5+PuXkkKFbL3p0EBPat95CScaKpKXRj82VnPyy4mMZsoJ65pz0CKn7iwckXtarU0qHP2enZKY8X94DW3V0+VEFFuOaX8TvfppZhPvzxRZWARPN7seJebReea2XhSA7tRjaLhGVcgM4CPlaV4UBS1rgUybF3G0cqvCbTdqhos951oZ1WjvQxqUk0DUMk2iCTupCBkkJ/EdMSZvf6TiqDYIdukx6X7g6jMoCDxYODkLO/too41pHFcf+iVlnS13pz9oRABmmkMRgYGqXKq41P0lgORRj55KkQq7Y0HIykeGjzWJXsP7YtfZh3myCplkEGRAWrH2gzA9p5qrd31GFT3deXKVoTaA3Dq4XI2PtxP3pWc4EkIu21Pa4c6r15p++n6jga/2CqZ1N0pP4KDnIGFrSzjxLwrUPkXn2SKqDYshhCfxk1TwJctWXdzubSqOAX9tWIt1SbkU1GVhJMNrJi5fVGZhjsboOJm77RzloOqR161E/NNz0XQM+HQcaaZr3YT1dxeLPF04fi1hURmMijaFUMZq5Um5MznG+4Y7+m9M/m/h6vscycwfO7E7U2ewD++Z98w4FBhzDZab6s=
  template:
    metadata:
      name: authelia-oidc-headlamp
      namespace: headlamp
