apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cert-manager-cluster-view-cluster-role-binding.yaml
  - resources/ops-non-namespaced-view-cluster-role-binding.yaml
  - resources/ops-non-namespaced-view-cluster-role.yaml
buildMetadata: [managedByLabel]
