apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/httproute.yaml
  - resources/pvc-config.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
images:
  - name: jellyfin
    newName: docker.io/jellyfin/jellyfin
    newTag: "12.0"
buildMetadata: [managedByLabel]
