apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/httproute.yaml
  - resources/httproute-intranet.yaml
  - resources/network-policy.yaml
  - resources/pv-media.yaml
  - resources/pvc-cache-images.yaml
  - resources/pvc-config.yaml
  - resources/pvc-media.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml
labels:
  - includeTemplates: true
    includeSelectors: false
    pairs:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
images:
  - name: jellyfin
    newName: docker.io/jellyfin/jellyfin
    newTag: "12.2"
buildMetadata: [managedByLabel]
