---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-lastfm
  namespace: media
spec:
  encryptedData:
    apikey: AgCP454AiEYuuqmFd/j7RKJJh9mfeQEOBJOqF/jeRhm0QwDmAKWvhazByAU6FmAIWyuSiNrPZn5yr/B0oKbE5S+/r3b/98uwJqbjid8zZv0sKbq+TaYbRtQ+eddZXrWBecHxKHVbB1j4v0pKQB6HQK570Xi12asq4V7CRoPdzvhJvpmCQWFQvpd0KAv1HqeS2FJn5O/sv2jNWorYO5lieXQ6ixHR7cs4716ykI4fgvd/9BjYbXLCkd/fbwOZQ328egOGeXWoFXcxKO0vn2OY2jVcdOb/BwQsnbbR+MKCL2NrctU6HFgY/QMht3TuWr1aAg/KcH7Qa8v20okkOVLHNc410DGkeWSTvKIm/uRXQ1G7sUCxNtJbYWul56wjB+cdiWuohvGmq6nESdoZed2783SYHYIYl3pgCWbde9EvQoLZ25oFZxX8k0w/sK7NwOSDJZokjRx+xZxJI3/nuCcSleaMbtWZitOKNr07vtcspTOnqYmytt7wEbQhyhs7LsdjEj4MyWCY9kYuC4Kc+p6QeygGQxxmTyCEBMevUbckep7+cUSwQwdUsr07SW4JLfwfbMAVDnw4En92qbwMqjwcTAjn0T1NczfFv5rkVRyvMQIpqTqrjo8v9V56i9JshNYk/yNR/V00fs3x2yDfcDgo3ssKdOTGXV4+xFJTV0WYib+133MEAy2V+LHy3RUPXq8elqtU0jKldOkN7oz3lMdXiDGDyoxCZ1VR9roODS57AbNGsg==
    secret: AgCNLhz+5y/T0Flufzd36ja58hjUssaPpfL+htQPD4DgRdN3QxicpxouBN1lHO+jJSj5TsODgdmfYCgB1KOe2ZUNV+Mvr6h3U6ZKlejgLK/AXJrwnJUudLAwPWIg5rWqYSfz0njmsI09DqrCtNMUHS8PwRZbjhLVIQLbqQlWEkmlTKAd/sbdLyBjLqEvSGIDs58nts0GSZ5o1X8TGowBWTu22M2XpkS0Ppfk+uWU/M1lFZ8qjn0G/qRWRRZcHhqnHfX0RV2VbLVMcxfjOJed43QrtiLN7YP5e91aNbHuRhu8Fi6MueboQsQWHAYSR63+CVrBFitFe+GXozNEdtZPFkKezB916kVzWluf9es+OVquuidVGqEnPNWY7DeUQ53U1AB+3ZFZZIbkPVlax1TMbHdn+5SU/4oSmoObm2yyvgg9o6ifsmm2mVGlucPSweq2LlmounoUPFqgUAvAd6mLzVZd7C83oSAdgfiUHsQCG0wRuc/+JwTRSYCYbNleCsl8rRyxQSiUX2ad7Q/LmCvcuQIT2tVujkAF8SWNa+u737hpxmy7YsfXWzNo/t79+bg40gWxqRe3C2Y43ITQetCLtoKBHqo5J5EwF88ED5+w27lOA2aWr0vqwXCdoSe8763fUUbBqnDXrhRynT0OLoEtEW129RMEGPjBnkSujfDxhmbDX7CLBJJZID/Isicffz1eAZDuiG9lbBaOeX1nuGaRUsi+A516xIXVRy4RHjvtwkDJXA==
  template:
    metadata:
      name: navidrome-lastfm
      namespace: media
