apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/deployment.yaml
  - ./resources/httproute.yaml
  - ./resources/network-policy.yaml
  - ./resources/pvc-config.yaml
  - ./resources/pvc-data.yaml
  - ./resources/pv-data.yaml
  - ./resources/service.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
images:
  - name: sonarr
    newName: linuxserver/sonarr
    newTag: 4.0.17.2952-ls310
buildMetadata: [managedByLabel]
