dashboard:
  external:
    hostname: null
traefik:
  # started from https://doc.traefik.io/traefik/v3.4/setup/kubernetes/
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

  # Configure Network Ports and EntryPoints
  # EntryPoints are the network listeners for incoming traffic.
  ports:
    web:
      port: 80
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    websecure:
      port: 443

  service:
    spec:
      # Preserve client IP addresses
      externalTrafficPolicy: Local

  # Enables the dashboard in Secure Mode
  api:
    dashboard: true
    insecure: false

  ingressClass:
    enabled: true
    isDefaultClass: false
    name: traefik-external

  gatewayClass:
    enabled: true
    name: traefik-external

  gateway:
    name: traefik-external
    annotations:
      # cert-manager.io/cluster-issuer: TODO
    listeners:
      web:
        port: 80
        protocol: HTTP
        namespacePolicy:
          from: All

  # Providers controls which resources Traefik watches to find routing configuration.
  providers:
    # traefik IngressRoute
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true
      ingressClass: traefik-external
    kubernetesGateway:
      enabled: true

  logs:
    general:
      level: INFO
    # This enables access logs, outputting them to Traefik's standard output by default.
    # The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
    access:
      enabled: true

  # Enables Prometheus metrics
  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: true

  tracing:
    otlp:
      enabled: true
      grpc:
        enabled: true
        endpoint: "tempo-distributor.tempo.svc.cluster.local:4317"
        insecure: true
