apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-recipes-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  bootstrap:
    initdb:
      database: tandoor_recipes
      owner: tandoor_recipes

  storage:
    size: 1Gi
