apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-recipes-media
spec:
  storageClassName: mercury-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
