---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor-recipes
  namespace: tandoor-recipes
spec:
  encryptedData:
    secret_key: AgBKCRAC0WaKhm4Fu+UaqjP+7SlHsfseKnVNpdm/fuvX9BUUwlAtpJdWbyw0vsBQc8hahdGEJMK+51s5uM8o8ik5ikVeJw4h7OZowO7GwRIJkO+83PCflAM7FQG9r+amHB2PhUCO15xihqe/4gu0Gc2xm2hztMqq5jdp992fqP6bZTQjkZDc1tZ9op8uSJ+QAN4i0A7PX5YDWSTpGheQpGW//8/xBASFRK3O0jpHfJ0Jsqe456DZwSkxYvoNT2i4XJxaegLndfpYW3TdpsVfo2RhopwQzUscMpfhVjRpymeVAV04J+AI056nCnvU7hQBoIU4pYBk/0UPI4yFaz3Y4yHWr5yZhaXO4pltQvZdab03Zu9dgHQZMiA0PvY0AeiPgDYf6lNoh/YuIxYvdV01PQmCuJ0bAfwPYfR53dP9e9Nx/ER77WxPb4B940ceKvpfk4sIzUi/RMgoARVu3j9EsEeJ15gQvn4EVCGbgK7kv8Tcr87JiJGnIij2nfjV5uvEX9vB01DKgpcfqcF07d4fXH/ovomFWPXiYNgJG31MeqGvxdWMqdDoGoPKa9w/KNqqSut6RELhvOp+DQ5Ac+47ezUKkmGKv6gdRgVvxDwmxn7a2wprrdnjPKQmR9bEkM7OCMWLFbsJ8Ov+h9F7DvJynyxqBJ/UQVsyCqil6t63hsQDpkZHMSctpPJYzrCH6GkPIAuO0b3rVWYW92KTUdBPsyJXK8FMAmEZMMw3WKJPxP9i04OUfcxzxFGK5W6UxvVbe6lP9w==
  template:
    metadata:
      name: tandoor-recipes
      namespace: tandoor-recipes
