apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-vtt
spec:
  template:
    spec:
      containers:
        - name: foundryvtt-web
          # https://hub.docker.com/r/felddy/foundryvtt#environment-variables
          env:
            - name: FOUNDRY_HOSTNAME
              value: "allen.foundry-vtt.wildfreddy.fivebytestudios.com"
            - name: FOUNDRY_LOCAL_HOSTNAME
              value: "allen.foundry-vtt.int.fivebytestudios.com"
            - name: FOUNDRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: foundry-vtt-user-allen
                  key: username
            - name: FOUNDRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foundry-vtt-user-allen
                  key: password
            - name: FOUNDRY_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: foundry-vtt-admin-allen
                  key: key
