apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: traefik
  listeners:
{{- range $name, $listener := .Values.external.gateway.listeners.https }}
    - name: {{ $name }}
      port: 9443
      protocol: HTTPS
      hostname: {{ $listener.hostname }}
      allowedRoutes:
{{- if $listener.namespace }}
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $listener.namespace }}
{{- else }}
        namespaces:
          from: Same
{{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ default (printf "%s-tls" $name) $listener.certificateRef }}
{{- end }}
    - name: web-ext
      port: 9080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
