{{- range $name, $certificate := .Values.intranet.wildcardCertificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
spec:
  secretName: {{ default $name $certificate.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: intranet-dns01-prod
  dnsNames:
    {{- toYaml $certificate.dnsNames | nindent 4 }}
{{- end }}
