apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - resources/namespace.yaml
  - resources/authelia-middleware.yaml
  - resources/role-binding-media-ops-view.yaml
  - resources/sealed-secret-protonvpn-credentials.yaml
  - resources/sealed-secret-navidrome-lastfm.yaml
buildMetadata: [managedByLabel]
