apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - resources/namespace.yaml
  - resources/authelia-middleware.yaml
  - resources/jellyfin-cache-images-pvc.yaml
  - resources/jellyfin-external-httproute.yaml
  - resources/jellyfin-intranet-httproute.yaml
  - resources/jellyfin-pv-media.yaml
  - resources/jellyfin-pvc-media.yaml
  - resources/role-binding-ops-aggregate-to-view.yaml
  - resources/sealed-secret-protonvpn-credentials.yaml
  - resources/sealed-secret-spotify-navidrome.yaml
buildMetadata: [managedByLabel]
