apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-api-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - gateways/status
      - gatewayclasses
      - gatewayclasses/status
      - httproutes
      - httproutes/status
    verbs:
      - get
      - list
      - watch
