apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/network-policy.yaml
  - resources/service.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: iperf3
      app.kubernetes.io/name: iperf3
images:
  - name: alpine
    newName: alpine
    newTag: "3.23.3"
buildMetadata: [managedByLabel]
