---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-tempo
  namespace: tempo
spec:
  encryptedData:
    ACCESS_KEY: AgCtWHjmhpQtrTAcI5U9GQG/GP9eDUJi5otHh3I+0EDMCdl4xoUTY0Tj9fSL8YC5m7dmKBcK3JsP4CJmunkQd50GnHnJaVcy3bCWOBTzkoZgb6aVFikQm2RXwa/qCKrJCcgIrEwXXdDG2WB4KoQMky4z2D2DrdKltISOJ5ViwPSv23fvIj75rabrxQcv3c6c2L4PxTavLeD6CpueHlGW0k/w4fHie7OhbnsdryeRpEs9agGYbUmgNRy+BP7aN1c97bcOuKE0cCQNCn5CWCtgCvKC3qCJbJAlY0byuMus1Tq9KpvFvha6mB3ZOUOf43OaDhuUk2eIjLDiC1SZ3N8B/DmsHbNNi8xi6eCV6bzGLxri4CCM/+TKhAvq++kuAy1+GE+Ts9zIDqiRAWWliYVITu9ITOfDwPvYES8SGNjW2zycOr4Xrhh01hXBXHvrsOi5ReR5rmZGLNII5pQc8IpBjHTNWTCol/Ib4OMtJRaT1lCxZSL3JSHuG6DeNikHEA04diFFUUkWpIj2m4aQj7FVHEXtZ0MIOy/bXq7CNDDTrofn/vONNIIl6pNzeTKdP0gKZD6IJq+aLa9jbKOq5emp74C+xeC5Sh4Aooxirzi39RiVxbUQZOoYiiPkd6dsbbbocrTcOyKl0E7gkpSldjIGCuQ9wrVmN8BGSXzAesgU9Z/T3Clb2dIj5tu8xx4UneKB3ocpd50WQIkfOAEgkU5FcDR5lQ0OYg==
    SECRET_KEY: AgCH67dmZHQb08v8P/4YL0pe9Zsou7st7lm3TLWF5PvXmu4DUq7yVdn7zWrkqvGqVSv/sL95RCpaFQ80GEV5TR/7Gkj5KlUy0po4lu6WdrJrgawoD8C9c4QnvASJJFvJQsz5vRio8xaqzrH/D+YCV0cKkUOAY1SXmbpEL1EMQ1yI4L43BlbmVChJziuYlT6YgGaqzFOWV6YeAIwEQzwKL2in2Q6piOaGYBlMBIMNkUSYFBRunqDlN2L3qOYJBfdbAcV6Eg4F9aKSDu2fYO0AMah/TZbOskrI4EToqT8D1Qf51K3PCWbC3l9Wo8uutTeOQ1C+EpQQXVAWyL8Akbbn6FS6mV0+Fh9OWjWKO2l8psWPD+iyYwnjrWXX4QfRSYu22wWHMHpG9kqeTC9SzuYQ+VqBRGQNZTsA+QFtRZIrf27ebW4+WFIELZlT8FUPcuBkRth8xFXDS73KO++xnuOdbRTVLBGyMXxtkrtSnGClv7sRdg3VMJPV406ZWkYNiP1u5Z3CK1j5VPQOy8JxSYhdl9gV7NUO9kBgAkkyJ49M/EHyUR52Vb4wR2zRmiriZmAZ2skVGzC4bukBYnD6zF3lj3eU2VEG3z2i/52RnR6U4W49LWC2DwBJcWGArqNW6cv0eGB2Y8yszdmscnzA/1GlTpEcdDMEd4V12VGqOxSXTSDixV36qdaXuTwLcFCSqN2IaKFC0PIhgJGnsbIKm+qgoSeMv2QyPoQSvViKTNegeN3mK0rFIfeZSa4g
  template:
    metadata:
      name: seaweedfs-tempo
      namespace: tempo
