---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: foundry-vtt-admin-allen
  namespace: foundry-vtt
spec:
  encryptedData:
    key: AgAyGg4f8bUacKXMM7xucwkc2nd+BXL6hEhfB+GRLqA0EJOaycLkL0sITRQDN/Jebo5ucsvkmP17kcaYw7LFeZegHursf/D3MxNjEnSv0M/bFOT6w4slHgwRQRAfrxKIbnjw90N9jmgqqY+RhO5E+lYPHcXM/Fyn8sODDFOajjpcEfFCt9sdmUufRG8HC3kruGoMfBIy5xqmnpgOBDaqGuQkb6XXlovLRhkeO6E6GQTNH9XaSDa+pmJNUewyYkriJs4Ce8mLYPX4NI1zqQnZ2mRso+XySchJiWL1+0Jx3viElG6a0EBXkmEEjMnE+a7/tGqsreOwtsRSkoPPI3ZKwgAXMd1vS5ZtCs2DEj/FO8XOG7n5bd6w6XL7AWJkOZ60kkE1DD1LOO0A2cgWBCF40yP/ow6wuUtsv7n5V+FxjZB14sooc1AiEV0Tj0xdv66iE4uZYOW6JEEEpueW/u4jiuqzuvRohSYiOKh/wLkU5FLX928LE7TyblXRLi5meAGUESp6uVrqTgplAry8zJakHGDFBm7iSJGy///gu5yevNQ74nnC3VnamtTUZa6jaIzTRHumbEKLAJkl7ZPCcDdsT57/cXcnoGaSHPvy66xQRf9O6/RH24rtIBZrYPWX8onUitoln4ysKWc2WBjBTUL93aJbwze78JjjdmL3CChHqcefrKGUng1KWWQViK5HrJ53e4uglOw0SYsZZuN7tk6xdgOe0HR0dQ5gheUAjyegONF3SA==
  template:
    metadata:
      name: foundry-vtt-admin-allen
      namespace: foundry-vtt
