---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: foundry-vtt-user-allen
  namespace: foundry-vtt
spec:
  encryptedData:
    password: AgAjqYjbjPFv5skqMITwrTUESJ52KIFtgOoswy2sLpXZ27OWIsJg9DpmOEtC8DvVSmA3K40SAmpEwo36PQRyGTvFtOnHK/cPhfRMuAWXqd2C5NQIRI0PzoOV004I/bGgixuOUU+xIc3Fk1i+rFWXm/C4+eRE0Ricz9VfptMgnnIHYFRkjqG3j9BC+/VjV8jlZDJRyN+ADyw8JRGGofqqoLdw2b4HuEcyNPEABMIHoni6BZKA+PCjJwYLMzkqPBTU7IcqGbBot6E/y0mj7MLF9fgz6XlGYDjvQRzu01djntRmPglvqJ4RqJWgdZriKUXpHUjbo8be+hKdkKqol6+7FfbLFYtrt9tZDjq00HWcIj3JzXVlL5mAITC58B+PbHm9VJ0T5a6Els8opsb3/C2Us+HtyJkFOyFQn06oLKtH5+/LFb8Ulhb93nOvTymjylM5hXXf1o8Jmza6784aetZ8rDIQFN6WzQAk1o3UJNCVuHdb0nhoWfQlp6oaCM18Qlvy9PzcjkNLJD2iP5BJgmYmDsHb33WXVY/n/Tri4J5tic4Aq+2KLgw9vjoyv/KuuQ0+bTwrs6JDSKXaMRjZrIMlMDLS8t2/3//QJgHV4uH6terfRLTyDtH/VgJH5LC536ckT2KNsRz2MsH/cfhdXEYVBOWMiByccmq+s57h8AVKrle7QxOYDFAJPFvFaP58O9Mb4/X2BT0RsBJjIOXGlAl3S8jIpcjf
    username: AgBPnroW25ru1CvwaDsqDYrlao5EEc/QVTeKpNK7yG2KuxY9nKV6B3MF92zRN4Wh7juYisvYM5Qu1qLualMH6jk9nZbPE/Scthl6A4l9+jh6qu7LF5aHEdu+zWFrNsTC4UqLAuSheSY5F01baFs5Kw94SLXfoYbpm4u4ZxoLaqRt6Ax2/R4fZvj0nLKYMV2rkzPzRoh9palKUXcng/VtRTC9QMrOl2FjC+M4KD+6OCsnxagTrv1maPkT5BE3HgeRaaljz0RN08o/LztXhVJqlhIiSm4/yrkIiBLV7xlsfjUTI6+E0tGlPtn7I0hv/pkRT18aL0knPafQrIxRERffoKC/bUex6SzhrZ8d4kdq72xfWhTXwWS6sskf6dXQ6ZGeTbPf2MI07ZnqE8k4mOd23b1E77LhA0pu8D0HE2f65zfEce/dVLYNPvX21aB/RUrtOIpGBUTlGgZ9QCLrez3QL8Z+dOy2xruvHEeG7ru75yJV852d9xftD7/syUWrYcs53yssQM+xTERLzoWoUUP1KumktRoWvGObwD1Y9dWQfMpZgwe4//WFD27aOYHYjEZ+mu8RD36t9/tZAXi3MEUldoMnfy12TkenoYwbD3c1ugWAcT0JrMi3YbDO78yJID7mPJcDlpVkrashv0kTx2/ckZclUPkzZNq1SCoDUm/edkKOivuMFwZ5qQxh6XAnqjE16GaumeV8FApTNTG6ANDuTECE6idJrB/oQw==
  template:
    metadata:
      name: foundry-vtt-user-allen
      namespace: foundry-vtt
