apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/httproute-intranet.yaml
patches:
  - path: patches/deployment-environment.yaml
  - path: patches/httproute-external-hostname.yaml
nameSuffix: -allen
