apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cnpg-cluster.yaml
  - resources/deployment.yaml
  - resources/httproute.yaml
  - resources/pvc-media.yaml
  - resources/pvc-static.yaml
  - resources/sealed-secret.yaml
  - resources/service.yaml
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/instance: tandoor-recipes
      app.kubernetes.io/name: tandoor-recipes
images:
  - name: tandoor-recipes
    newName: vabene1111/recipes
    newTag: 2.6.15
buildMetadata: [managedByLabel]
